version: '3.5'
services:
  translationhub:
    build:
      context: TranslationHUB/
    ports:
      - "3000:3000"
      - "4040:4040"
    restart: always 
    depends_on:
      - eventmanager
  
  eventmanager:
    build:
      context: OMRPipeline/eventmanager
    ports:
      - "5000:5000"
  
  layoutanalysis:
    build:
      context: OMRPipeline/layoutanalysis
    ports:
      - "5005:5005"