- hosts: localhost
  tasks:
    - name: Install docker package
      pip: name=docker-py
    - name: Create a network
      docker_network:
        name: readsco
    
    - name: Download event manager image
      docker_image:
        name: readsco/eventmanager
        source: pull
        tag: latest
        force_tag: yes
      notify: 
        - Remove Event Manager
        - Start New Event Manager 

    - name: Download translation hub image
      docker_image:
        name: readsco/translationhub
        source: pull
        tag: latest
        force_tag: yes
      notify:
        - Remove Translation Hub
        - Start New Translation Hub
    
    - name: Download score recognition image
      docker_image:
        name: readsco/scorerecognition
        source: pull
        tag: latest
        force_tag: yes
      notify: 
        - Remove Score Recognition
        - Start New Score Recognition

    - name: Download layout analysis image
      docker_image:
        name: readsco/layoutanalysis
        source: pull
        tag: latest
        force_tag: yes
      notify:
        - Remove Layout Analysis
        - Start New Layout Analysis
  
  handlers:
    - name: Remove Event Manager
      docker_container:
        name: eventmanager
        state: absent
        purge_networks: yes
    - name: Start New Event Manager
      docker_container:
        name: eventmanager
        image: "readsco/eventmanager:latest"
        ports:
          - "5000:5000"
        networks:
          - name: readsco
    - name: Remove Translation Hub
      docker_container:
        name: translationhub
        state: absent
        purge_networks: yes
    - name: Start New Translation Hub
      docker_container:
        name: translationhub
        image: "readsco/translationhub:latest"
        ports:
          - "3000:3000"
        networks:
          - name: readsco
    - name: Remove Score Recognition
      docker_container:
        name: scorerecognition
        state: absent
        purge_networks: yes
    - name: Start New Score Recognition
      docker_container:
        name: scorerecognition
        image: "readsco/scorerecognition:latest"
        ports:
          - "5006:5006"
        networks:
          - name: readsco
    - name: Remove Layout Analysis
      docker_container:
        name: layoutanalysis
        state: absent
        purge_networks: yes
    - name: Start New Layout Analysis
      docker_container:
        name: layoutanalysis
        image: "readsco/layoutanalysis:latest"
        ports:
          - "5005:5005"
        networks:
          - name: readsco
    
        